"""initial migration

Revision ID: 111d0eddabb3
Revises: 
Create Date: 2026-04-10 15:01:31.441773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111d0eddabb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eathquakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eathquakes')
    # ### end Alembic commands ###
